name: Release

on:
  push:
    tags:
      - 'v*' # Trigger on any tag starting with "v", e.g., v2.0.0

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-4-dev libadwaita-1-dev libglib2.0-dev pkg-config build-essential libsecret-1-dev fuse
          
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          
      - name: Run Build Script
        run: |
          chmod +x build_test_appimage.sh
          # The appimagetool requires FUSE
          # Normally installing fuse on ubuntu-24.04 is enough to run the AppImageTool.
          APPIMAGE_EXTRACT_AND_RUN=1 ./build_test_appimage.sh
          
      - name: Read Version from Cargo.toml
        id: get_version
        run: |
          # Extract version number without the 'v'
          VERSION=$(grep '^version' Cargo.toml | head -1 | cut -d '"' -f 2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          
      - name: Release AppImage
        uses: softprops/action-gh-release@v2
        with:
          files: "Mimick-*.AppImage"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
